name: Cypress tests

on:
  push:
    branches:
      - main

jobs:
  cypress-tests-chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Chrome
        uses: actions/checkout@v4

      - name: Install Dependencies Chrome
        run: npm install

      - name: Run Cypress Tests Chrome
<<<<<<< HEAD
        run: npm run cypress:run:chrome
=======
        run: npm run cypress:run:chrome
>>>>>>> 672adaced4ce28c432daf5ccfbaac890590dab78
